### ISSUE TITLE
How do I pass client oauth into Resource()?

### ISSUE THREAD

**Issue by joetito1** [googleapis/nodejs-resource-manager#411]
I'm trying to use Resource() to get projects for the currently authenticated user who I've authenticated with OAuth. Could someone please explain how I would pass an exsiting oauth client into this call please?

`const [projects] = await new Resource().getProjects();`

**Comment by sofisl** [comment]
Hi @joetito1, our recommended way of authenticating is to use [Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc). I will close this issue for now since we are migrating this repository to [google-cloud-node](https://github.com/googleapis/google-cloud-node). If you continue running into problems, please reopen the issue in that repo. Thank you!
